[package]
name = "gi_gen"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globset = "0.4.10"
home = "0.5.4"
tempfile = "3.4.0"
