name: Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v

      - name: Create dist/ dir
        run: mkdir dist

      - name: Generate build files
        uses: chenasraf/go-cross-build@v1
        with:
          platforms: "linux/amd64, darwin/amd64, windows/amd64" # , darwin/arm64' # '
          package: ""
          name: "gi_gen"
          compress: "true"
          dest: "dist"
      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
